export const database = {
  personaggi: [
    "Un cercatore di tesori", "Un neonazista", "Un'indossatrice", "Un'attrice di teatro",
    "Un hooligan", "Un animalista", "Un camorrista", "Un gondoliere", "Un eschimese",
    "Un astronauta", "Un generale dell'esercito", "Un contadino", "Un investigatore privato",
    "Una barista", "Un influencer", "Un ladro", "Un calciatore", "Una spia", "Un musicista",
    "Un ingegnere", "Un vampiro", "Una casalinga", "Un adolescente", "Un inventore",
    "Una cantante", "Un clown", "Un prete", "Una maga", "Un pirata", "Una guida turistica",
    "Un marinaio", "Una principessa", "Un robot", "Un tifoso", "Un farmacista", "Una sposa",
    "Un fotografo", "Un profugo", "Un pilota d’aereo", "Una star del cinema", "Un bibliotecario",
    "Un avvocato", "Una babysitter", "Un architetto", "Una psicologa", "Un DJ", "Una nonna",
    "Un artista", "Un calzolaio", "Un pescatore", "Un pittore", "Un giornalista", "Un attore",
    "Un vigile del fuoco", "Un insegnante", "Un criminale", "Un meccanico", "Un pugile",
    "Un poliziotto", "Un avventuriero", "Un barbiere", "Un operatore sanitario", "Una guida alpina",
    "Un capitano di nave", "Una suora", "Un pilota di Formula 1", "Un geologo", "Un medico",
    "Una ricercatrice", "Un politico", "Una ballerina", "Un tatuatore", "Un fornaio", "Un hacker",
    "Un programmatore", "Un ambientalista", "Un giocatore di poker", "Un archeologo", "Un bagnino",
    "Un autista", "Un giardiniere", "Una guida safari", "Un poeta", "Un produttore musicale",
    "Un cantante folk", "Un corriere", "Una guardia del corpo", "Un venditore ambulante",
    "Un cartografo", "Un eremita", "Un maestro di danza", "Un pilota di drone", "Un costruttore",
    "Un mago", "Una guida turistica"
  ],
  luoghi: [
    "In discoteca", "A un funerale", "In un castello in Scozia", "In piazza a Capodanno",
    "In gelateria", "In una pista di pattinaggio", "A un concorso di bellezza",
    "In una stazione ferroviaria", "In un rifugio di montagna", "Al centro commerciale",
    "In un museo", "Su un set cinematografico", "In un parco divertimenti", "In una sala giochi",
    "Al tavolo di un casinò", "In una foresta", "Su un ponte", "Nel deserto", "A bordo di una nave",
    "In una sala d’attesa", "In un quartiere malfamato", "In una casa infestata",
    "In uno studio di registrazione", "In una scuola", "In una biblioteca", "In una palestra",
    "In un ristorante di lusso", "In una lavanderia automatica", "In una fattoria", "Su una spiaggia",
    "In una metropolitana", "Su una montagna innevata", "In un ospedale", "In un luna park",
    "In un ufficio postale", "In un mercato rionale", "In una villa abbandonata", "In una prigione",
    "In un laboratorio scientifico", "In un aeroporto", "In una sala d’esame", "In una sala conferenze",
    "In una tenda da campeggio", "In un centro estetico", "In una scuola di cucina", "In una piscina",
    "In una stazione di polizia", "In un teatro"
  ],
  azioni: [
    "Fanno la dichiarazione dei redditi", "Riparano un macchinario", "Addobbano l'albero di Natale",
    "Si stanno lasciando", "Fanno una raccolta fondi", "Protestano", "Cercano casa",
    "Cercano di fuggire da una situazione", "Discutono di politica", "Partecipano a un quiz televisivo",
    "Vendono qualcosa per strada", "Preparano una sorpresa", "Si perdono in un luogo",
    "Cercano di convincere qualcuno", "Creano una nuova identità", "Collaborano per vincere una sfida",
    "Insegnano qualcosa a qualcuno", "Organizzano un colpo", "Si nascondono da un pericolo",
    "Fanno una proposta di matrimonio", "Cercano di risolvere un malinteso", "Litigano per soldi",
    "Costruiscono qualcosa", "Affrontano una paura", "Fanno un viaggio insieme",
    "Lottano per lo stesso obiettivo", "Affrontano una sfida impossibile", "Si perdono in una foresta",
    "Lottano per sopravvivere", "Tentano di rubare qualcosa", "Creano un piano di fuga",
    "Discutono su una decisione importante", "Tentano di nascondere un segreto",
    "Si preparano per un evento importante", "Devono convincere una giuria", "Cercano di salvare qualcuno",
    "Si prendono cura di un animale", "Organizzano una festa", "Scrivono un messaggio importante",
    "Cambiano completamente look", "Esplorano un luogo sconosciuto", "Collaborano per risolvere un mistero",
    "Cercano di capire cosa fare", "Studiano per un esame", "Aiutano qualcuno in difficoltà",
    "Tentano di battere un record", "Creano un'invenzione", "Raccolgono informazioni"
  ]
};
